// <auto-generated />
namespace OldLot.Dados.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Ajustesnasrelações : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ajustesnasrelações));
        
        string IMigrationMetadata.Id
        {
            get { return "201606280406091_Ajustes nas relações"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
